### PR TITLE
Find better issue id (ie. linear ...) in the branch name

### PR DESCRIPTION
**Pull request by mpatou**
The issue might not be at the beginning or people might not use a - but a _ or no separator

### CODE REVIEW

**Review by yashNaN — COMMENTED** [review]
Oo, i think this actually works out for me too because my branches are usually of the form `<username>/<team>-<id_number>_branch name`. Like `ynannapaneni/FDBCORE-11111_blah_something`. 

But like in the long run though for an open source tool should we be searching for issue id's in the branch name? That might not be applicable for most people.

**Comment by mpatou** [comment]
> Oo, i think this actually works out for me too because my branches are usually of the form `<username>/<team>-<id_number>_branch name`. Like `ynannapaneni/FDBCORE-11111_blah_something`.
> 
> But like in the long run though for an open source tool should we be searching for issue id's in the branch name? That might not be applicable for most people.

You're write but it's only helping, I can make this an opt-in or an opt-out, or I can make it so that you can provide your own regex to catch issue id if you want.

**Comment by yashNaN** [comment]
Hmm providing your own regex in the config file might be the best way.

**Review by yashNaN — APPROVED** [review]
I'll bug haneesh tonight to approve this. LGTM

**Review by haneeshr — APPROVED** [review]

**Comment by mpatou** [comment]
> Hmm providing your own regex in the config file might be the best way.
@yashNaN  I agree.
Can you file an issue ? I'll try to track that.

**Pull request merged**
